apiVersion: v1
kind: Service
metadata:
  name: {{ include "hr-assistant.fullname" . }}-hr-policy-db
  labels:
    {{- include "hr-assistant.labels" . | nindent 4 }}
    genai: hr-policy-db
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "hr-assistant.selectorLabels" . | nindent 4 }}
    genai: hr-policy-db
