apiVersion: v1
kind: Service
metadata:
  name: {{ include "hr-assistant.fullname" . }}-hr-assistant
  labels:
    {{- include "hr-assistant.labels" . | nindent 4 }}
    genai: hr-assistant
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "hr-assistant.selectorLabels" . | nindent 4 }}
    genai: hr-assistant
